type: pipeline
experiment_name: john-rai
compute: azureml:rai-cluster

inputs:
  target_column_name: income
  my_training_data:
    dataset: azureml:Adult_Train_PQ:1
    mode: ro_mount
  my_test_data:
    dataset: azureml:Adult_Test_PQ:1
    mode: ro_mount

outputs:
  my_model_directory:
    mode: upload
  rai_insights_dashboard:
    mode: upload
  model_info:
    mode: upload

settings:
  component_job:
    datastore: azureml:workspaceblobstore
    environment: azureml:AML-RAI-Environment:2

jobs:

  train-model:
    code:
      local_path: src
    command: python train.py --train_data ${{inputs.training_data}} --target_column ${{inputs.target_column_name}} --model_output ${{outputs.model_output}} 
    environment: azureml:AML-RAI-Environment:2
    inputs:
      training_data: ${{inputs.my_training_data}}
      target_column_name: ${{inputs.target_column_name}}
    outputs:
      model_output: ${{outputs.my_model_directory}}

  register-model-job:
    type: component_job
    component: azureml:register_model:2
    inputs:
      model_input_path: ${{jobs.train-model.outputs.model_output}}
      model_base_name: component_registered_lr_01
    outputs:
      model_info_output_path: ${{outputs.model_info}}

  create-rai-job:
    type: component_job
    component: azureml:rai_insights_constructor:2
    inputs:
      title: With just the OSS
      task_type: classification
      model_info_path: ${{jobs.register-model-job.outputs.model_info_output_path}}
      train_dataset: ${{inputs.my_training_data}}
      test_dataset: ${{inputs.my_test_data}}
      target_column_name: ${{inputs.target_column_name}}
      categorical_column_names: '["Race", "Sex", "Workclass", "Marital Status", "Country", "Occupation"]'
    outputs:
      rai_insights_dashboard: ${{outputs.rai_insights_dashboard}}

  explain_01:
    type: component_job
    component: azureml:rai_insights_explanation:2
    inputs:
      comment: Some random string
      rai_insights_dashboard: ${{jobs.create-rai-job.outputs.rai_insights_dashboard}}

  causal_01:
    type: component_job
    component: azureml:rai_insights_causal:2
    inputs:
      rai_insights_dashboard: ${{jobs.create-rai-job.outputs.rai_insights_dashboard}}
      treatment_features: '["Age", "Sex"]'
      heterogeneity_features: '["Marital Status"]'

  counterfactual_01:
    type: component_job
    component: azureml:rai_insights_counterfactual:2
    inputs:
      rai_insights_dashboard: ${{jobs.create-rai-job.outputs.rai_insights_dashboard}}
      total_CFs: 10
      desired_class: opposite

  error_analysis_01:
    type: component_job
    component: azureml:rai_insights_erroranalysis:2
    inputs:
      rai_insights_dashboard: ${{jobs.create-rai-job.outputs.rai_insights_dashboard}}
      filter_features: '["Race", "Sex", "Workclass", "Marital Status", "Country", "Occupation"]'

  gather_01:
    type: component_job
    component: azureml:rai_insights_gather:2
    inputs:
      constructor: ${{jobs.create-rai-job.outputs.rai_insights_dashboard}}
      insight_1: ${{jobs.causal_01.outputs.causal}}
      insight_2: ${{jobs.counterfactual_01.outputs.counterfactual}}
      insight_3: ${{jobs.error_analysis_01.outputs.error_analysis}}
      insight_4: ${{jobs.explain_01.outputs.explanation}}