$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
experiment_name: rai_adult_census
type: pipeline

inputs:
  target_column_name: income
  my_training_data:
    type: uri_file
    path: azureml:Adult_Train_MLT:1
    mode: download
  my_test_data:
    type: uri_file
    path: azureml:Adult_Test_MLT:1
    mode: download

outputs:
  my_model_directory:
    mode: upload
  rai_insights_dashboard:
    mode: upload
  model_info:
    mode: upload

settings:
  default_compute: azureml:gpu-cluster
  datastore: azureml:workspaceblobstore

jobs:
  train_model:
    code: src
    command: python train.py --train_data ${{inputs.training_data}} --target_column ${{inputs.target_column_name}} --model_output ${{outputs.model_output}} 
    environment: azureml:AML-RAI-Environment:2
    inputs:
      training_data: ${{parent.inputs.my_training_data}}
      target_column_name: ${{parent.inputs.target_column_name}}
    outputs:
      model_output: ${{parent.outputs.my_model_directory}}

  register_model_job:
    type: command
    component: azureml:register_model:2
    inputs:
      model_input_path: ${{parent.jobs.train_model.outputs.model_output}}
      model_base_name: component_registered_lr_01
    outputs:
      model_info_output_path: ${{parent.outputs.model_info}}

  create_rai_job:
    type: command
    component: azureml:rai_insights_constructor:2
    inputs:
      title: With just the OSS
      task_type: classification
      model_info_path: ${{parent.jobs.register_model_job.outputs.model_info_output_path}}
      train_dataset: ${{parent.inputs.my_training_data}}
      test_dataset: ${{parent.inputs.my_test_data}}
      target_column_name: ${{parent.inputs.target_column_name}}
      categorical_column_names: '["Race", "Sex", "Workclass", "Marital Status", "Country", "Occupation"]'
    outputs:
      rai_insights_dashboard: ${{parent.outputs.rai_insights_dashboard}}

  explain_01:
    type: command
    component: azureml:rai_insights_explanation:2
    inputs:
      comment: Some random string
      rai_insights_dashboard: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}

  causal_01:
    type: command
    component: azureml:rai_insights_causal:2
    inputs:
      rai_insights_dashboard: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}
      treatment_features: '["Age", "Sex"]'
      heterogeneity_features: '["Marital Status"]'

  counterfactual_01:
    type: command
    component: azureml:rai_insights_counterfactual:2
    inputs:
      rai_insights_dashboard: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}
      total_CFs: 10
      desired_class: opposite

  error_analysis_01:
    type: command
    component: azureml:rai_insights_erroranalysis:2
    inputs:
      rai_insights_dashboard: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}
      filter_features: '["Race", "Sex", "Workclass", "Marital Status", "Country", "Occupation"]'

  gather_01:
    type: command
    component: azureml:rai_insights_gather:2
    inputs:
      constructor: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}
      insight_1: ${{parent.jobs.causal_01.outputs.causal}}
      insight_2: ${{parent.jobs.counterfactual_01.outputs.counterfactual}}
      insight_3: ${{parent.jobs.error_analysis_01.outputs.error_analysis}}
      insight_4: ${{parent.jobs.explain_01.outputs.explanation}}

  scorecard_01:
    type: command
    component: azureml://registries/azureml/components/microsoft_azureml_rai_tabular_score_card/versions/0.2.0
    inputs:
      dashboard: ${{parent.jobs.gather_01.outputs.dashboard}}
      pdf_generation_config:
        type: uri_file
        path: ./adult_analyse_scorecard_config/pdf_gen.json
        mode: download
